[package]
name = "n10_2"
version = "0.1.0"
edition = "2021"

[lib]
name = "aggregator"
path = "src/aggregator.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
